variable "resource_prefix" {
  type        = string
  description = "Naming prefix to use for resources to be provisioned"
}

variable "log_retention_in_days" {
  type        = string
  description = "Number of days CloudWatch logs for all ECS task containers should be retained."
  default     = "30"
}

variable "app_port" {
  type    = string
  default = 443
}

## Web container configuration

variable "web_image" {
  type        = string
  description = "Name of Docker image to be pushed to ECR. It should not include the tag."
}

variable "web_version" {
  type        = string
  description = "Tag of Docker image that should be used when publishing to ECR and referencing from ECS Task Definition. Incrementing this value will trigger a docker push to the ECR repository."
}

variable "web_cpu" {
  type    = string
  default = "128"
}

variable "web_memory" {
  type    = string
  default = "256"
}

variable "account_name" {
  type        = string
  description = "Name representing the current AWS account to be injected into web container environment variables"
  default     = "Unknown"
}

variable "web_environment_variables" {
  type        = list(map(string))
  description = "Additional environment variables to be added to web container definition"
  default     = []
}

## reverse_proxy container configuration

variable "reverse_proxy_version" {
  type        = string
  description = "Tag of reverse_proxy Docker image that will be used to pull from GitLab and push to ECR. Incrementing this will trigger a docker push to the ECR repository."
}

variable "app_domain" {
  type        = string
  description = "The domain at which the application will be registered"
}

variable "reverse_proxy_cpu" {
  type    = string
  default = "64"
}

variable "reverse_proxy_memory" {
  type    = string
  default = "128"
}

variable "reverse_proxy_cert_country" {
  type        = string
  default     = ""
  description = "Subject Attribute C for self-signed SSL cert generated by nginx_reverse_proxy"
}

variable "reverse_proxy_cert_state" {
  type        = string
  default     = ""
  description = "Subject Attribute ST for self-signed SSL cert generated by nginx_reverse_proxy"
}

variable "reverse_proxy_cert_locality" {
  type        = string
  default     = ""
  description = "Subject Attribute L for self-signed SSL cert generated by nginx_reverse_proxy"
}

variable "reverse_proxy_cert_organization" {
  type        = string
  default     = ""
  description = "Subject Attribute O for self-signed SSL cert generated by nginx_reverse_proxy"
}

variable "reverse_proxy_cert_organizational_unit" {
  type        = string
  default     = ""
  description = "Subject Attribute OU for self-signed SSL cert generated by nginx_reverse_proxy"
}

variable "reverse_proxy_cert_email_address" {
  type        = string
  default     = ""
  description = "Subject Attribute emailAddress for self-signed SSL cert generated by nginx_reverse_proxy"
}

variable "reverse_proxy_timeout" {
  type        = string
  default     = "60"
  description = "Timeout (in seconds) for nginx_reverse_proxy"
}

## xray container configuration

variable "xray_cpu" {
  type    = string
  default = "64"
}

variable "xray_memory" {
  type    = string
  default = "128"
}
